# Generated by Django 3.1 on 2020-09-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('img', models.ImageField(upload_to='photoshare/images/', verbose_name='Image')),
                ('title', models.TextField(max_length=200, verbose_name='Title')),
                ('published', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
