# Generated by Django 3.1 on 2020-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0003_addpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
    ]
