# Generated by Django 3.1 on 2020-09-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0006_auto_20200906_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
