# Generated by Django 3.1 on 2020-09-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0007_auto_20200906_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='img',
        ),
        migrations.RemoveField(
            model_name='addpost',
            name='published',
        ),
        migrations.RemoveField(
            model_name='addpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='addpost',
            name='username',
        ),
        migrations.AlterField(
            model_name='addpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
