# Generated by Django 2.0.4 on 2020-09-06 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoshare', '0008_auto_20200906_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='addpost',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='addpost',
            name='title',
            field=models.TextField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='addpost',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
